<a href="https://colab.research.google.com/github/kalswjd/DA_School_1/blob/main/%08%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%EC%8A%A4%EC%BF%A8_0523_2%E1%84%8B%E1%85%B5%E1%86%AF%E1%84%8E%E1%85%A1_%E1%84%87%E1%85%A9%E1%86%A8%E1%84%89%E1%85%B3%E1%86%B8_%E1%84%8B%E1%85%A8%E1%84%8C%E1%85%A6_my%ED%92%80%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
z=np.zeros(10)

In [4]:
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
a=np.array([range(10,50)])

In [7]:
print(a)

[[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
  34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]]


In [8]:
b=np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
c=np.ones(25).reshape(5,5)
for i in range(1,4):
    c[i][1:4]=0

In [14]:
print(c)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
import random

In [18]:
np.random.random((3,3,3))

array([[[0.62147948, 0.64200782, 0.9629163 ],
        [0.04891602, 0.57607701, 0.24611   ],
        [0.77807008, 0.38470745, 0.99798145]],

       [[0.50467135, 0.111571  , 0.01092357],
        [0.46100408, 0.69789395, 0.62534248],
        [0.95247421, 0.20050615, 0.11982994]],

       [[0.78217041, 0.9114277 , 0.23469602],
        [0.36762653, 0.7267976 , 0.53986627],
        [0.98101666, 0.86155947, 0.94683088]]])

In [20]:
a=np.random.random((10,10))

In [21]:
a.min()

0.0039082940210780626

In [23]:
a.max()

0.9982335549023528

In [24]:
b=np.random.random((30))

In [27]:
b.mean()

0.5038287623159456

In [31]:
a=np.ones((5,3))
b=np.ones((3,2))
print(a)
print(b)
print(np.dot(a,b))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [36]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.zeros(3)
C =np.add(A,B)
C

array([5, 7, 9])

In [39]:
C=np.negative(A)
C

array([-1, -2, -3])

In [42]:
a=np.random.random(10)
a.argmax()

6

In [43]:
a[6]=0

In [44]:
a

array([0.10538795, 0.16556854, 0.0638866 , 0.14716864, 0.58585644,
       0.77703983, 0.        , 0.20517714, 0.15396008, 0.69204106])

In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('arr에서 최댓값:', np.max(arr))
print('arr에서 최댓값인 6이 위치한 인덱스:',np.argmax(arr))
print('arr에서 각 행(axis=0)별로 최댓값을 반환:', np.max(arr, axis=0))
print('arr에서 각 열(axis=1)별로 최댓값을 반환:', np.max(arr, axis=1))
print('arr에서 각 행(axis=0)별로 최댓값의 인덱스를 반환:',np.argmax(arr, axis=0))
print('arr에서 각 열(axis=1)별로 최댓값의 인덱스를 반환:',np.argmax(arr, axis=1))


arr에서 최댓값: 6
arr에서 최댓값인 6이 위치한 인덱스: 5
arr에서 각 행(axis=0)별로 최댓값을 반환: [4 5 6]
arr에서 각 열(axis=1)별로 최댓값을 반환: [3 6]
arr에서 각 행(axis=0)별로 최댓값의 인덱스를 반환: [1 1 1]
arr에서 각 열(axis=1)별로 최댓값의 인덱스를 반환: [2 2]
