<a href="https://colab.research.google.com/github/kalswjd/DA_School_1/blob/main/%08%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%EC%8A%A4%EC%BF%A8_0524_2%E1%84%8B%E1%85%B5%E1%86%AF%E1%84%8E%E1%85%A1_%E1%84%87%E1%85%A9%E1%86%A8%E1%84%89%E1%85%B3%E1%86%B8_%E1%84%8B%E1%85%A8%E1%84%8C%E1%85%A6_my%ED%92%80%EC%9D%B42.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
z=np.zeros(10)

In [4]:
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
a=np.array([range(10,50)])

In [7]:
print(a)

[[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
  34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]]


In [8]:
b=np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
c=np.ones(25).reshape(5,5)
for i in range(1,4):
    c[i][1:4]=0

In [14]:
print(c)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
import random

In [18]:
np.random.random((3,3,3))

array([[[0.62147948, 0.64200782, 0.9629163 ],
        [0.04891602, 0.57607701, 0.24611   ],
        [0.77807008, 0.38470745, 0.99798145]],

       [[0.50467135, 0.111571  , 0.01092357],
        [0.46100408, 0.69789395, 0.62534248],
        [0.95247421, 0.20050615, 0.11982994]],

       [[0.78217041, 0.9114277 , 0.23469602],
        [0.36762653, 0.7267976 , 0.53986627],
        [0.98101666, 0.86155947, 0.94683088]]])

In [20]:
a=np.random.random((10,10))

In [21]:
a.min()

0.0039082940210780626

In [23]:
a.max()

0.9982335549023528

In [24]:
b=np.random.random((30))

In [27]:
b.mean()

0.5038287623159456

In [31]:
a=np.ones((5,3))
b=np.ones((3,2))
print(a)
print(b)
print(np.dot(a,b))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [36]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.zeros(3)
C =np.add(A,B)
C

array([5, 7, 9])

In [39]:
C=np.negative(A)
C

array([-1, -2, -3])

In [42]:
a=np.random.random(10)
a.argmax()

6

In [43]:
a[6]=0

In [44]:
a

array([0.10538795, 0.16556854, 0.0638866 , 0.14716864, 0.58585644,
       0.77703983, 0.        , 0.20517714, 0.15396008, 0.69204106])

In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('arr에서 최댓값:', np.max(arr))
print('arr에서 최댓값인 6이 위치한 인덱스:',np.argmax(arr))
print('arr에서 각 행(axis=0)별로 최댓값을 반환:', np.max(arr, axis=0))
print('arr에서 각 열(axis=1)별로 최댓값을 반환:', np.max(arr, axis=1))
print('arr에서 각 행(axis=0)별로 최댓값의 인덱스를 반환:',np.argmax(arr, axis=0))
print('arr에서 각 열(axis=1)별로 최댓값의 인덱스를 반환:',np.argmax(arr, axis=1))


arr에서 최댓값: 6
arr에서 최댓값인 6이 위치한 인덱스: 5
arr에서 각 행(axis=0)별로 최댓값을 반환: [4 5 6]
arr에서 각 열(axis=1)별로 최댓값을 반환: [3 6]
arr에서 각 행(axis=0)별로 최댓값의 인덱스를 반환: [1 1 1]
arr에서 각 열(axis=1)별로 최댓값의 인덱스를 반환: [2 2]


In [6]:
# .view() 메서드 예제
arr1 = np.array([1, 2, 3, 4, 5])
view_arr1 = arr1.view()

print(view_arr1)
# 출력: [1 2 3 4 5]

# .astype() 메서드 예제
arr2 = np.array([1.1, 2.2, 3.3, 4.4, 5.5])
int_arr2 = arr2.astype(int)

print(int_arr2)
# 출력: [1 2 3 4 5]

[1 2 3 4 5]
[1 2 3 4 5]


In [10]:
b=np.random.randint(0,6,(3,10),dtype=int)

In [11]:
b

array([[0, 4, 0, 5, 5, 3, 1, 4, 4, 3],
       [1, 3, 5, 5, 3, 1, 0, 2, 2, 3],
       [0, 2, 4, 5, 3, 5, 2, 0, 3, 1]])

In [14]:
b.any()

True

In [15]:
c=np.random.uniform(0,1,10)

In [16]:
c

array([0.55012276, 0.31942793, 0.76901081, 0.53718035, 0.22795409,
       0.3487538 , 0.08376413, 0.11575418, 0.93947573, 0.39679336])

In [18]:
num=0.5
np.abs(c-num).argmin()

3

In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6], [3, 4, 5]])
flatten_arr = arr.flatten()
flatten_arr

array([1, 2, 3, 4, 5, 6, 3, 4, 5])

In [24]:
flatten_arr.argmax()

5

In [25]:
flatten_arr[5] = 10

In [26]:
flatten_arr

array([ 1,  2,  3,  4,  5, 10,  3,  4,  5])

In [28]:
a=np.random.randint(0,10,(3,4,3,4))

In [29]:
a

array([[[[9, 6, 2, 2],
         [5, 3, 6, 1],
         [1, 7, 5, 1]],

        [[5, 2, 2, 2],
         [0, 1, 8, 3],
         [5, 4, 0, 2]],

        [[1, 1, 1, 7],
         [9, 5, 8, 5],
         [1, 5, 7, 0]],

        [[4, 6, 7, 6],
         [8, 4, 9, 6],
         [7, 7, 3, 2]]],


       [[[0, 5, 1, 2],
         [2, 3, 5, 2],
         [6, 5, 8, 6]],

        [[5, 0, 8, 8],
         [0, 3, 5, 4],
         [8, 9, 7, 0]],

        [[4, 0, 0, 5],
         [5, 1, 7, 4],
         [2, 7, 4, 0]],

        [[6, 9, 2, 0],
         [7, 1, 5, 8],
         [2, 4, 5, 9]]],


       [[[2, 7, 4, 9],
         [8, 5, 0, 0],
         [1, 4, 1, 2]],

        [[0, 3, 0, 4],
         [4, 7, 1, 2],
         [3, 1, 1, 7]],

        [[7, 2, 2, 5],
         [5, 1, 0, 2],
         [6, 7, 4, 1]],

        [[4, 9, 3, 6],
         [4, 0, 6, 0],
         [7, 4, 5, 5]]]])

In [30]:
a.sum(axis = (-2,-1))

array([[48, 34, 50, 69],
       [45, 57, 39, 58],
       [43, 33, 42, 53]])

In [37]:
a = np.arange(25).reshape(5,5)


In [38]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
a[[0,1]] = a[[1,0]]


In [40]:
a

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
b=np.random.normal(0,1,100)

In [43]:
b

array([ 0.0805751 , -1.34987358,  1.05390327, -0.96459483, -0.44468684,
        0.13865016,  0.25225711,  0.21486977, -1.52371714,  0.35724715,
       -1.09415629,  0.303142  , -0.01892134,  0.04625123,  2.17810523,
        0.61835712,  0.8805051 , -1.78873141,  2.05813113, -0.82656823,
        0.42146277, -0.48366095,  0.15407062,  0.39805073, -0.45012649,
        1.32564251,  0.0538087 , -0.27607304, -0.22097015, -0.62111622,
        0.73314521, -0.09137723,  0.72156252,  0.14266539,  1.07456963,
        0.48558139, -0.89916863, -0.9110179 ,  0.09652473,  0.82548514,
       -0.04138401, -0.82002432,  0.36177808, -1.13742947, -1.14576743,
        0.29010827,  1.1181422 ,  0.55354032, -0.29853566, -0.21427045,
        0.95176158, -0.90297505, -0.69436652,  0.57240859,  1.15003984,
       -0.9457822 ,  0.11524383, -0.36673778,  0.17268248, -0.20103057,
       -0.44906138,  0.18533419, -1.05424461,  0.22465598, -0.64775392,
       -1.02079816, -1.605648  , -0.19932302, -1.04594186,  0.55

In [44]:
np.random.shuffle(b)

In [45]:
b[np.argsort(b)[-5:]]

array([1.57527043, 1.65158548, 1.93985568, 2.05813113, 2.17810523])