<a href="https://colab.research.google.com/github/kalswjd/DA_School_1/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%EC%8A%A4%EC%BF%A8_0522_NumPy_1%EC%9D%BC%EC%B0%A8_%EB%B3%B5%EC%8A%B5_%EC%98%88%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

### 1. array()
차원별 배열 생성

In [4]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

[1 2 3 4 5]


In [5]:
arr_1d = np.array([i for i in range(1,10, 2)])
print(arr_1d)

[1 3 5 7 9]


In [6]:
print(np.array(range(10)))
print(np.array(range(1, 11)))
print(np.array(range(2, 11, 2)))
print(np.array(range(10, 2, -1)))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
[10  9  8  7  6  5  4  3]


In [7]:
arr_1d = np.array([1, 2, 3, 4, 5],dtype='f')
print(arr_1d)

[1. 2. 3. 4. 5.]


In [8]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [9]:
arr_2d = np.array(range(1,13, 2)).reshape(2,3)
print(arr_2d)

[[ 1  3  5]
 [ 7  9 11]]


In [11]:
# Error : 요소의 개수가 reshape의 행렬 개수에 맞게 설정해야 합니다.
arr_2d = np.array(range(1,13, 2)).reshape(2,4)
print(arr_2d)

ValueError: ignored

In [12]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 2. arange()

In [16]:
print(np.array(range(10)))
print(np.array(range(1, 11)))
print(np.array(range(2, 11, 2)))
#print(np.array(range(2, 11, 0.5)))
print(np.array(range(10, 2, -1)))
#print(np.array(range(10, 2, -0.5)))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
[10  9  8  7  6  5  4  3]


In [18]:
print(np.arange(10))
print(np.arange(1, 11))
print(np.arange(2, 11, 2))
print(np.arange(2, 11, .5))
print(np.arange(10, 2, -1))
print(np.arange(10, 2, -.5))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
[ 2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5
  9.   9.5 10.  10.5]
[10  9  8  7  6  5  4  3]
[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5]


### 3. 다양한 배열 만들기


In [19]:
# 일차원으로 변경
arr_3d.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
# 0으로 채워진 배열 생성
z = np.zeros((2,2))
z

array([[0., 0.],
       [0., 0.]])

In [21]:
# 1로 채워진 배열 생성
one1 = np.ones((2,2))
one1

array([[1., 1.],
       [1., 1.]])

In [22]:
# 내가 원하는 값으로 채워진 배열 생성
f = np.full((2,2),10)
f

array([[10, 10],
       [10, 10]])

In [23]:
# 단위행렬
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 4. 넘파이 함수를 이용해서 문제풀기


4.1 주어진 여러 개의 1차원 배열을 연결하여 하나의 큰 1차원 배열로 반환하세요.

In [26]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9, 10])

# concat 함수

arr_a = np.concatenate(arr1, arr2, arr3)

TypeError: ignored

4.2 주어진 2차원 배열에서 각 열의 평균값을 계산하여 새로운 1차원 배열로 나타내세요.

In [28]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# mean() 함수 응용하기

4.3 주어진 2차원 배열에서 각 행의 최대값을 구하여 1차원 배열로 반환하세요.

In [29]:
# np.max()

4.4 0에서 1사이의 값으로 크기 10개의 1차원 배열을 만들어주세요.

In [30]:
# linspace()

4.5 주어진 1차원 배열에서 짝수인 요소들의 합을 계산하는 함수 sum_of_evens를 작성하세요.

- 
def sum_of_evens(arr: np.ndarray) -> int:


In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(sum_of_evens(arr))

NameError: ignored

4.6 수평분할, 수직분할, 수평 스택, 수직 스택 문제를 풀어봅시다.

In [ ]:
# 분할할 배열 생성
arr = np.arange(1, 13).reshape((3, 4))
print("원본 배열:")
print(arr)

In [ ]:
# 1. 수평분할하기 -> 다시 원본으로 스택쌓기

# 2. 수직분할하기 -> 다시 원본으로 스택쌓기

4.7 배열에서 조건에 맞는 값 반환하는 문제를 풀어봅시다.

In [ ]:
# 조건 : 값을 10으로 나누었을 때 나머지가 0이면 원래 값 출력, 아니면 0으로 출력하세요.
arr = np.arange(0, 100, 5).reshape((5,4))

4.8 [3x3]배열 lst 중 짝수만 뽑아내는 부울린 인덱싱 배열(numpy 배열)을 사용하여 짝수 배열 n 을 만드시오

In [ ]:
lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
a = np.array(lst)

4.9 각도를 이용해서 삼각함수를 만들어봅시다.

In [ ]:
angle = np.pi / 3 # 라디안 표기 = 60도 
# 360도는 2라디안 으로, 180도는 1라디안으로 표현합니다.

angle

4.10 조건함수를 사용해서  짝수조건을 만족하는 요소의 값이 2배로 만드는 배열을 만드시오.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

In [ ]:
# 4.1 정답
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9, 10])
np.concatenate([arr1,arr2,arr3])

In [ ]:
# 4.2 정답

np.mean(arr, axis=0) 


In [ ]:
# 4.3 정답

np.max(arr, axis=1)

In [ ]:
# 4.4 정답
np.linspace(0,1,10)

In [ ]:
# 4.5 정답

def sum_of_evens(arr: np.ndarray) -> int:
    evens = arr[arr % 2 == 0]  # 짝수인 요소 선택
    return np.sum(evens)  # 짝수인 요소들의 합 반환

In [ ]:
# 4.6 정답
arr_split = np.hsplit(arr, 2)
print("수평 분할 결과:")
print(arr_split)

arr_1 = arr_split[0]
arr_2 = arr_split[1]
arr_stack = np.hstack((arr_1, arr_2))
print(arr_stack)

In [ ]:
# 수직 분할
arr_split = np.vsplit(arr, 3)
print("수직 분할 결과:")
print(arr_split)

arr_1 = arr_split[0]
arr_2 = arr_split[1]
arr_3 = arr_split[2]
arr_stack = np.vstack((arr_1, arr_2, arr_3))
print(arr_stack)

In [ ]:
# 4.7 정답
# 조건 : 값을 10으로 나누었을 때 나머지가 0이면 원래 값 출력, 아니면 0으로 출력하세요.
arr = np.arange(0, 100, 5).reshape((5,4))
print(np.where(arr%10==0, arr,0))

In [ ]:
# 4.8 정답

# 3가지 정답이 있습니다. 인덱싱 배열을 이용하기
bool_indexing_array = np.array([
    [False,  True, False],
    [True, False,  True],
    [False,  True, False]
])
 
n = a[bool_indexing_array];
print(n)    

In [ ]:
# 배열 a 에 대해 짝수면 True, 홀수면 False 
bool_indexing = (a % 2 == 0)
print(bool_indexing)
print(a[bool_indexing])

In [ ]:
# 간단한 조건으로 호출하기
n = a[ a % 2 == 0 ]
n

In [ ]:
# 4.9 정답이
# 사인 함수 계산
sin_value = np.sin(angle)
print("사인 값:", sin_value)

# 코사인 함수 계산
cos_value = np.cos(angle)
print("코사인 값:", cos_value)

# 탄젠트 함수 계산
tan_value = np.tan(angle)
print("탄젠트 값:", tan_value)

In [ ]:
# 4.10 정답
new_arr = np.where(arr % 2 == 0, arr * 2, arr)
print("조건을 만족하는 요소를 2배로:", new_arr)