<a href="https://colab.research.google.com/github/kalswjd/DA_School_1/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%EC%8A%A4%EC%BF%A8_0522_NumPy_1%EC%9D%BC%EC%B0%A8_%EB%B3%B5%EC%8A%B5_%EC%98%88%EC%A0%9C_%ED%92%80%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#1.array()

In [ ]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
b = np.array([i for i in range(1,10,2)])
print(b)

[1 3 5 7 9]


In [ ]:
print(np.array(range(10)))

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(np.array(range(1,11)))

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(np.array(range(2,11,2)))

[ 2  4  6  8 10]


In [ ]:
print(np.array(range(10,2,-1)))

[10  9  8  7  6  5  4  3]


In [ ]:
c = np.array([1,2,3,4,5],dtype='f')
print(c)

[1. 2. 3. 4. 5.]


In [ ]:
d = np.array([[1,2,3],[4,5,6]])
print(d)

[[1 2 3]
 [4 5 6]]


In [ ]:
e = np.array(range(1,13,2)).reshape(2,3)

In [ ]:
print(e)

[[ 1  3  5]
 [ 7  9 11]]


In [ ]:
f = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#2.arange()

In [ ]:
print(np.array(range(10)))
print(np.array(range(1, 11)))
print(np.array(range(2, 11, 2)))
#print(np.array(range(2, 11, 0.5)))
print(np.array(range(10, 2, -1)))
#print(np.array(range(10, 2, -0.5)))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
[10  9  8  7  6  5  4  3]


In [ ]:
print(np.arange(10))
print(np.arange(1, 11))
print(np.arange(2, 11, 2))
print(np.arange(2, 11, .5))
print(np.arange(10, 2, -1))
print(np.arange(10, 2, -.5))

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
[ 2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5
  9.   9.5 10.  10.5]
[10  9  8  7  6  5  4  3]
[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5]


#3.다양한 배열

In [ ]:
g = e.ravel()

In [ ]:
print(g)

[ 1  3  5  7  9 11]


In [ ]:
h = np.zeros((2,2))

In [ ]:
print(h)

[[0. 0.]
 [0. 0.]]


In [ ]:
i = np.ones((2,2))

In [ ]:
print(i)

[[1. 1.]
 [1. 1.]]


In [ ]:
j = np.full((2,2),10)

In [ ]:
print(j)

[[10 10]
 [10 10]]


In [ ]:
k = np.eye(4)

In [ ]:
print(k)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#4.문제풀이

In [ ]:
#4.1
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9, 10])

concat = np.concatenate((arr1,arr2,arr3))

In [ ]:
print(concat)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#4.2
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# mean() 함수 응용하기

arr1 = np.mean([arr[0]])
arr2 = np.mean([arr[1]])
arr3 = np.mean([arr[2]])
mean = ([arr1,arr2,arr3])

In [ ]:
print(mean)

[2.0, 5.0, 8.0]


In [ ]:
#4.3
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr1 = np.max([arr[0]])
arr2 = np.max([arr[1]])
arr3 = np.max([arr[2]])
max = ([arr1,arr2,arr3])

In [ ]:
print(max)

[3, 6, 9]


In [45]:
#4.4  0에서 1사이의 값으로 크기 10개의 1차원 배열
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [46]:
#4.5
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

def sum_of_evens(arr):
    evens = arr[arr % 2 == 0]
    return np.sum(evens)


In [47]:
sum_of_evens(arr)

30

In [48]:
#4.6
arr = np.arange(1, 13).reshape((3, 4))
print("원본 배열:")
print(arr)

원본 배열:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [51]:
arr_split = np.hsplit(arr, 2)
print("수평 분할 결과:")
print(arr_split)

arr_1 = arr_split[0]
arr_2 = arr_split[1]
arr_stack = np.hstack((arr_1, arr_2))
print(arr_stack)

수평 분할 결과:
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
